# COGS 118A - Project Checkpoint

# Names

Hopefully your team is at least this good. Obviously you should replace these with your names.

- Pratheek Sankeshi
- Ria Singh
- Neil Bajaj
- Shenova Davis

# Abstract 
The goal of this project is to predict whether to approve a credit card for an applicant based on a variety of factors that were asked on their application. We will predict using a machine learning algorithm. The data we will be using is from the Kaggle dataset: A Credit Card Dataset for Machine Learning. The link is https://www.kaggle.com/datasets/caesarmario/application-data/. We will be using factors such as Total Income, Education Type, Applicant Age, etc. More will be described in the data section. Furthermore, we will drop unnecessary columns like Owned Phone, Owned Email, etc while also replacing null values to perform EDA. We will then run various supervised machine learning algorithms to create models to predict the data and use the best one. The performance will be measured on how accurately we predict the data against the status column of the data which is whether the application was approved or not.

# Background

Fill in the background and discuss the kind of prior work that has gone on in this research area here. **Use inline citation** to specify which references support which statements.  You can do that through HTML footnotes (demonstrated here). I used to reccommend Markdown footnotes (google is your friend) because they are simpler but recently I have had some problems with them working for me whereas HTML ones always work so far. So use the method that works for you, but do use inline citations.

Here is an example of inline citation. After government genocide in the 20th century, real birds were replaced with surveillance drones designed to look just like birds<a name="lorenz"></a>[<sup>[1]</sup>](#lorenznote). Use a minimum of 2 or 3 citations, but we prefer more <a name="admonish"></a>[<sup>[2]</sup>](#admonishnote). You need enough citations to fully explain and back up important facts. 

Remeber you are trying to explain why someone would want to answer your question or why your hypothesis is in the form that you've stated. 

# Problem Statement

Clearly describe the problem that you are solving. Avoid ambiguous words. The problem described should be well defined and should have at least one ML-relevant potential solution. Additionally, describe the problem thoroughly such that it is clear that the problem is quantifiable (the problem can be expressed in mathematical or logical terms), measurable (the problem can be measured by some metric and clearly observed), and replicable (the problem can be reproduced and occurs more than once).

# Data

UPDATED FROM PROPOSAL!

You should have obtained and cleaned (if necessary) data you will use for this project.

Please give the following infomration for each dataset you are using
- link/reference to obtain it
- description of the size of the dataset (# of variables, # of observations)
- what an observation consists of
- what some critical variables are, how they are represented
- any special handling, transformations, cleaning, etc you have done should be demonstrated here!


# Proposed Solution

In this section, clearly describe a solution to the problem. The solution should be applicable to the project domain and appropriate for the dataset(s) or input(s) given. Provide enough detail (e.g., algorithmic description and/or theoretical properties) to convince us that your solution is applicable. Make sure to describe how the solution will be tested.  

If you know details already, describe how (e.g., library used, function calls) you plan to implement the solution in a way that is reproducible.

If it is appropriate to the problem statement, describe a benchmark model<a name="sota"></a>[<sup>[3]</sup>](#sotanote) against which your solution will be compared. 

# Evaluation Metrics

Propose at least one evaluation metric that can be used to quantify the performance of both the benchmark model and the solution model. The evaluation metric(s) you propose should be appropriate given the context of the data, the problem statement, and the intended solution. Describe how the evaluation metric(s) are derived and provide an example of their mathematical representations (if applicable). Complex evaluation metrics should be clearly defined and quantifiable (can be expressed in mathematical or logical terms).

# Preliminary results

NEW SECTION!

Please show any preliminary results you have managed to obtain.

Examples would include:
- Analyzing the suitability of a dataset or alogrithm for prediction/solving your problem  #we will explain this part
- Performing feature selection or hand-designing features from the raw data. Describe the features available/created and/or show the code for selection/creation #make any nonnumbers into numbers
- Showing the performance of a base model/hyper-parameter setting.  Solve the task with one "default" algorithm and characterize the performance level of that base model. #refer below for all of this
- Learning curves or validation curves for a particular model
- Tables/graphs showing the performance of different models/hyper-parameters



This dataset is extremely suited for this problem since it has a column which is Status which tells based on the previous columns whether or not the credit card request was approved. This was also a dataset of over 10,000 datapoints which is good for our algorithm. We explained the reasoning for our algorithms in another section and our baseline is if its greater than the mean than we accept it. This is our baseline of baselines. Afterwards we will do do k-fold and use that as the baseline to test our hyperparameters and parameters in order to select the best models. 

In [43]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns    
from matplotlib.pyplot import figure
import sklearn
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
# use seaborn plotting defaults
import seaborn as sns; sns.set()
from sklearn.datasets import make_blobs

import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#models importing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB 

#linear svm stuff
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

from sklearn.kernel_ridge import KernelRidge

In [44]:
credit  = pd.read_csv('Application_Data.csv')
credit.head()

Applicant_ID Applicant_Gender  Owned_Car  Owned_Realty  Total_Children  \
0       5008806          M                1             1               0   
1       5008808          F                0             1               0   
2       5008809          F                0             1               0   
3       5008810          F                0             1               0   
4       5008811          F                0             1               0   

   Total_Income                                        Income_Type  \
0        112500  Working                                       ...   
1        270000  Commercial associate                          ...   
2        270000  Commercial associate                          ...   
3        270000  Commercial associate                          ...   
4        270000  Commercial associate                          ...   

                                      Education_Type  \
0  Secondary / secondary special                 ...   
1  Secondary / secondary special                 ...   
2  Secondary / secondary special                 ...   
3  Secondary / secondary special                 ...   
4  Secondary / secondary special                 ...   

                                       Family_Status  \
0  Married                                       ...   
1  Single / not married                          ...   
2  Single / not married                          ...   
3  Single / not married                          ...   
4  Single / not married                          ...   

                                        Housing_Type  ...  Owned_Work_Phone  \
0  House / apartment                             ...  ...                 0   
1  House / apartment                             ...  ...                 0   
2  House / apartment                             ...  ...                 0   
3  House / apartment                             ...  ...                 0   
4  House / apartment                             ...  ...                 0   

   Owned_Phone  Owned_Email  \
0            0            0   
1            1            1   
2            1            1   
3            1            1   
4            1            1   

                                           Job_Title Total_Family_Members  \
0  Security staff                                ...                    2   
1  Sales staff                                   ...                    1   
2  Sales staff                                   ...                    1   
3  Sales staff                                   ...                    1   
4  Sales staff                                   ...                    1   

   Applicant_Age  Years_of_Working  Total_Bad_Debt  Total_Good_Debt  Status  
0             59                 4               0               30       1  
1             53                 9               0                5       1  
2             53                 9               0                5       1  
3             53                 9               0               27       1  
4             53                 9               0               39       1  

[5 rows x 21 columns]

In [45]:
credit.dtypes

Applicant_ID             int64
Applicant_Gender        object
Owned_Car                int64
Owned_Realty             int64
Total_Children           int64
Total_Income             int64
Income_Type             object
Education_Type          object
Family_Status           object
Housing_Type            object
Owned_Mobile_Phone       int64
Owned_Work_Phone         int64
Owned_Phone              int64
Owned_Email              int64
Job_Title               object
Total_Family_Members     int64
Applicant_Age            int64
Years_of_Working         int64
Total_Bad_Debt           int64
Total_Good_Debt          int64
Status                   int64
dtype: object

In [46]:
#first we will only keep columns that we need. These columns are covered under Data along with status which says whether or not it was approved
credit = credit[["Applicant_Gender", "Applicant_Age","Owned_Realty","Total_Children", "Owned_Car", "Total_Income", "Housing_Type", "Total_Family_Members", "Education_Type", "Family_Status", 'Status']]

In [47]:
credit.head()

Applicant_Gender  Applicant_Age  Owned_Realty  Total_Children  Owned_Car  \
0          M                   59             1               0          1   
1          F                   53             1               0          0   
2          F                   53             1               0          0   
3          F                   53             1               0          0   
4          F                   53             1               0          0   

   Total_Income                                       Housing_Type  \
0        112500  House / apartment                             ...   
1        270000  House / apartment                             ...   
2        270000  House / apartment                             ...   
3        270000  House / apartment                             ...   
4        270000  House / apartment                             ...   

   Total_Family_Members                                     Education_Type  \
0                     2  Secondary / secondary special                 ...   
1                     1  Secondary / secondary special                 ...   
2                     1  Secondary / secondary special                 ...   
3                     1  Secondary / secondary special                 ...   
4                     1  Secondary / secondary special                 ...   

                                       Family_Status  Status  
0  Married                                       ...       1  
1  Single / not married                          ...       1  
2  Single / not married                          ...       1  
3  Single / not married                          ...       1  
4  Single / not married                          ...       1

In [48]:
print(len(credit.dtypes)) #same as the number of columns in data

11


In [49]:
#next we check for nulls and nans and if there exists any we will count them
#and decide to drop the row containing that datapooint

credit.isnull().values.any()
#so there isnt any nan values so we dont need to replace any values anywhere

False

In [50]:
#next is making all columns which arent numerical numerical
#first we will check which columns arent numerical
credit.dtypes

Applicant_Gender        object
Applicant_Age            int64
Owned_Realty             int64
Total_Children           int64
Owned_Car                int64
Total_Income             int64
Housing_Type            object
Total_Family_Members     int64
Education_Type          object
Family_Status           object
Status                   int64
dtype: object

In [51]:
#from the above we see that Applicant_Gender , Housing_Type , Education_Type , Family_Status
#check the unique values for applicant_gender
credit['Applicant_Gender'].unique()
#from below we see that its male or female

array(['M      ', 'F      '], dtype=object)

In [52]:
credit.head()

Applicant_Gender  Applicant_Age  Owned_Realty  Total_Children  Owned_Car  \
0          M                   59             1               0          1   
1          F                   53             1               0          0   
2          F                   53             1               0          0   
3          F                   53             1               0          0   
4          F                   53             1               0          0   

   Total_Income                                       Housing_Type  \
0        112500  House / apartment                             ...   
1        270000  House / apartment                             ...   
2        270000  House / apartment                             ...   
3        270000  House / apartment                             ...   
4        270000  House / apartment                             ...   

   Total_Family_Members                                     Education_Type  \
0                     2  Secondary / secondary special                 ...   
1                     1  Secondary / secondary special                 ...   
2                     1  Secondary / secondary special                 ...   
3                     1  Secondary / secondary special                 ...   
4                     1  Secondary / secondary special                 ...   

                                       Family_Status  Status  
0  Married                                       ...       1  
1  Single / not married                          ...       1  
2  Single / not married                          ...       1  
3  Single / not married                          ...       1  
4  Single / not married                          ...       1

In [53]:
def one_hot_encode(x:np.ndarray):
    # your code here
    uniqueValues = np.unique(x) #so the unique is not the same each time which can cause the names of the columns to be
    #incorrect so we will first sort it
    numUnique = len(np.unique(x))
    #print(sizeOfArrays)
    #print(type(uniqueValues))
    #oneHot = np.zeros((numUnique, len(x)))
    oneHot = np.zeros((len(x), numUnique))
    #print(uniqueValues)
    i = 0
    for val in x:
        oneHot[i][np.where(uniqueValues == val)[0][0]] = 1
        i += 1
    #print(oneHot)
    return uniqueValues, oneHot;

In [54]:
#housing one hot encoding
housing = credit['Housing_Type']
housing = np.array(list(housing))
housing
print(type(housing))


<class 'numpy.ndarray'>


In [55]:
namesForOneHotHousing, oneHotHousing = one_hot_encode(housing)
#oneHotHousing = arrHouse[:]
#namesForOneHotHousing = arrHouse[0]
print(namesForOneHotHousing)
print(oneHotHousing)
print(oneHotHousing.shape)

['Co-op apartment                                   '
 'House / apartment                                 '
 'Municipal apartment                               '
 'Office apartment                                  '
 'Rented apartment                                  '
 'With parents                                      ']
[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
(25128, 6)


In [56]:
sum(oneHotHousing[:,1])
print(sum((oneHotHousing))) #just shows how many in each category

[  152. 22096.   812.   199.   439.  1430.]


In [57]:
#namesForOneHotHousing = credit['Housing_Type'].unique()
print(namesForOneHotHousing[0])
for i in range(oneHotHousing.shape[1]):
    credit[namesForOneHotHousing[i]] = oneHotHousing[:,i]

Co-op apartment                                   


In [58]:
credit.head()

Applicant_Gender  Applicant_Age  Owned_Realty  Total_Children  Owned_Car  \
0          M                   59             1               0          1   
1          F                   53             1               0          0   
2          F                   53             1               0          0   
3          F                   53             1               0          0   
4          F                   53             1               0          0   

   Total_Income                                       Housing_Type  \
0        112500  House / apartment                             ...   
1        270000  House / apartment                             ...   
2        270000  House / apartment                             ...   
3        270000  House / apartment                             ...   
4        270000  House / apartment                             ...   

   Total_Family_Members                                     Education_Type  \
0                     2  Secondary / secondary special                 ...   
1                     1  Secondary / secondary special                 ...   
2                     1  Secondary / secondary special                 ...   
3                     1  Secondary / secondary special                 ...   
4                     1  Secondary / secondary special                 ...   

                                       Family_Status  Status  \
0  Married                                       ...       1   
1  Single / not married                          ...       1   
2  Single / not married                          ...       1   
3  Single / not married                          ...       1   
4  Single / not married                          ...       1   

   Co-op apartment                                     \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   House / apartment                                   \
0                                                1.0    
1                                                1.0    
2                                                1.0    
3                                                1.0    
4                                                1.0    

   Municipal apartment                                 \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Office apartment                                    \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Rented apartment                                    \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   With parents                                        
0                                                0.0   
1                                                0.0   
2                                                0.0   
3                                                0.0   
4                                                0.0

In [59]:
#okay next is education type
#education one hot encoding
education = credit['Education_Type']
education = np.array(list(education))
education
print(type(education))


<class 'numpy.ndarray'>


In [60]:
namesForOneHotEducation, oneHotEducation = one_hot_encode(education)
#oneHotHousing = arrHouse[:]
#namesForOneHotHousing = arrHouse[0]
print(namesForOneHotEducation)
print(oneHotEducation)
print(oneHotEducation.shape)

['Academic degree                                   '
 'Higher education                                  '
 'Incomplete higher                                 '
 'Lower secondary                                   '
 'Secondary / secondary special                     ']
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
(25128, 5)


In [61]:
sum(oneHotEducation[:,1])
print(sum((oneHotEducation))) #just shows how many in each category
print(sum(sum(oneHotEducation)))

[1.4000e+01 7.1320e+03 9.9300e+02 1.8700e+02 1.6802e+04]
25128.0


In [62]:
print(namesForOneHotEducation[0])
for i in range(oneHotEducation.shape[1]):
    credit[namesForOneHotEducation[i]] = oneHotEducation[:,i]
credit.head()

Academic degree                                   


Applicant_Gender  Applicant_Age  Owned_Realty  Total_Children  Owned_Car  \
0          M                   59             1               0          1   
1          F                   53             1               0          0   
2          F                   53             1               0          0   
3          F                   53             1               0          0   
4          F                   53             1               0          0   

   Total_Income                                       Housing_Type  \
0        112500  House / apartment                             ...   
1        270000  House / apartment                             ...   
2        270000  House / apartment                             ...   
3        270000  House / apartment                             ...   
4        270000  House / apartment                             ...   

   Total_Family_Members                                     Education_Type  \
0                     2  Secondary / secondary special                 ...   
1                     1  Secondary / secondary special                 ...   
2                     1  Secondary / secondary special                 ...   
3                     1  Secondary / secondary special                 ...   
4                     1  Secondary / secondary special                 ...   

                                       Family_Status  ...  \
0  Married                                       ...  ...   
1  Single / not married                          ...  ...   
2  Single / not married                          ...  ...   
3  Single / not married                          ...  ...   
4  Single / not married                          ...  ...   

   House / apartment                                   \
0                                                1.0    
1                                                1.0    
2                                                1.0    
3                                                1.0    
4                                                1.0    

   Municipal apartment                                 \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Office apartment                                    \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Rented apartment                                    \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   With parents                                        \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Academic degree                                     \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Higher education                                    \
0                                                0.0    
1                                                0.0    
2                                              

In [63]:
#next is family status
family = credit['Family_Status']
family = np.array(list(family))
family
print(type(family))

<class 'numpy.ndarray'>


In [64]:
namesForOneHotFamily, oneHotFamily = one_hot_encode(family)
#oneHotHousing = arrHouse[:]
#namesForOneHotHousing = arrHouse[0]
print(namesForOneHotFamily)
print(oneHotFamily)
print(oneHotFamily.shape)

['Civil marriage                                    '
 'Married                                           '
 'Separated                                         '
 'Single / not married                              '
 'Widow                                             ']
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
(25128, 5)


In [65]:
sum(oneHotFamily[:,1])
print(sum((oneHotFamily))) #just shows how many in each category
print(sum(sum(oneHotFamily)))

[ 2133. 17507.  1464.  3444.   580.]
25128.0


In [66]:
#next is Family_Status
credit['Family_Status'].unique()

array(['Married                                           ',
       'Single / not married                              ',
       'Civil marriage                                    ',
       'Separated                                         ',
       'Widow                                             '], dtype=object)

In [67]:
print(namesForOneHotFamily[0])
for i in range(oneHotFamily.shape[1]):
    credit[namesForOneHotFamily[i]] = oneHotFamily[:,i]
credit.head()

Civil marriage                                    


Applicant_Gender  Applicant_Age  Owned_Realty  Total_Children  Owned_Car  \
0          M                   59             1               0          1   
1          F                   53             1               0          0   
2          F                   53             1               0          0   
3          F                   53             1               0          0   
4          F                   53             1               0          0   

   Total_Income                                       Housing_Type  \
0        112500  House / apartment                             ...   
1        270000  House / apartment                             ...   
2        270000  House / apartment                             ...   
3        270000  House / apartment                             ...   
4        270000  House / apartment                             ...   

   Total_Family_Members                                     Education_Type  \
0                     2  Secondary / secondary special                 ...   
1                     1  Secondary / secondary special                 ...   
2                     1  Secondary / secondary special                 ...   
3                     1  Secondary / secondary special                 ...   
4                     1  Secondary / secondary special                 ...   

                                       Family_Status  ...  \
0  Married                                       ...  ...   
1  Single / not married                          ...  ...   
2  Single / not married                          ...  ...   
3  Single / not married                          ...  ...   
4  Single / not married                          ...  ...   

   Academic degree                                     \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Higher education                                    \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Incomplete higher                                   \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Lower secondary                                     \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Secondary / secondary special                       \
0                                                1.0    
1                                                1.0    
2                                                1.0    
3                                                1.0    
4                                                1.0    

   Civil marriage                                      \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   Married                                             \
0                                                1.0    
1                                                0.0    
2                                              

In [74]:
credit.shape

(25128, 27)

In [68]:
 #now we are done one hot encoding everything

In [69]:
#next is visualization


In [70]:
#Base Model is  just if the income is better than the mean than approve otherwise don't


#train test split
from sklearn.model_selection import train_test_split

train, test = train_test_split(credit, test_size=0.2)

In [71]:
print(train.shape)
train.head()

(20102, 27)


Applicant_Gender  Applicant_Age  Owned_Realty  Total_Children  \
15751          F                   44             0               1   
15626          F                   39             0               1   
16782          M                   30             1               0   
2380           F                   40             0               1   
14353          M                   41             1               2   

       Owned_Car  Total_Income  \
15751          0        112500   
15626          0         81000   
16782          1        225000   
2380           0        135000   
14353          1        180000   

                                            Housing_Type  \
15751  House / apartment                             ...   
15626  House / apartment                             ...   
16782  House / apartment                             ...   
2380   House / apartment                             ...   
14353  House / apartment                             ...   

       Total_Family_Members  \
15751                     3   
15626                     3   
16782                     2   
2380                      3   
14353                     4   

                                          Education_Type  \
15751  Higher education                              ...   
15626  Secondary / secondary special                 ...   
16782  Higher education                              ...   
2380   Secondary / secondary special                 ...   
14353  Higher education                              ...   

                                           Family_Status  ...  \
15751  Married                                       ...  ...   
15626  Married                                       ...  ...   
16782  Married                                       ...  ...   
2380   Married                                       ...  ...   
14353  Civil marriage                                ...  ...   

       Academic degree                                     \
15751                                                0.0    
15626                                                0.0    
16782                                                0.0    
2380                                                 0.0    
14353                                                0.0    

       Higher education                                    \
15751                                                1.0    
15626                                                0.0    
16782                                                1.0    
2380                                                 0.0    
14353                                                1.0    

       Incomplete higher                                   \
15751                                                0.0    
15626                                                0.0    
16782                                                0.0    
2380                                                 0.0    
14353                                                0.0    

       Lower secondary                                     \
15751                                                0.0    
15626                                                0.0    
16782                                                0.0    
2380                                                 0.0    
14353                                                0.0    

       Secondary / secondary special                       \
15751                                                0.0    
15626                                                1.0    
16782                                                0.0    
2380                                                 1.0    
14353                                                0.0    

       Civil marriage                                      \
15751                                                0.0    
15626                                                0.0    
16782                                                0.0

In [72]:
print(test.shape)
test.head()

(5026, 27)


Applicant_Gender  Applicant_Age  Owned_Realty  Total_Children  \
5122           F                   36             1               0   
20046          F                   39             0               0   
11689          F                   44             1               0   
5630           F                   49             0               0   
9852           M                   45             1               0   

       Owned_Car  Total_Income  \
5122           0        121500   
20046          1        225000   
11689          0        135000   
5630           1        240750   
9852           1        180000   

                                            Housing_Type  \
5122   House / apartment                             ...   
20046  House / apartment                             ...   
11689  House / apartment                             ...   
5630   With parents                                  ...   
9852   House / apartment                             ...   

       Total_Family_Members  \
5122                      2   
20046                     1   
11689                     2   
5630                      2   
9852                      2   

                                          Education_Type  \
5122   Secondary / secondary special                 ...   
20046  Higher education                              ...   
11689  Secondary / secondary special                 ...   
5630   Secondary / secondary special                 ...   
9852   Lower secondary                               ...   

                                           Family_Status  ...  \
5122   Civil marriage                                ...  ...   
20046  Single / not married                          ...  ...   
11689  Married                                       ...  ...   
5630   Civil marriage                                ...  ...   
9852   Married                                       ...  ...   

       Academic degree                                     \
5122                                                 0.0    
20046                                                0.0    
11689                                                0.0    
5630                                                 0.0    
9852                                                 0.0    

       Higher education                                    \
5122                                                 0.0    
20046                                                1.0    
11689                                                0.0    
5630                                                 0.0    
9852                                                 0.0    

       Incomplete higher                                   \
5122                                                 0.0    
20046                                                0.0    
11689                                                0.0    
5630                                                 0.0    
9852                                                 0.0    

       Lower secondary                                     \
5122                                                 0.0    
20046                                                0.0    
11689                                                0.0    
5630                                                 0.0    
9852                                                 1.0    

       Secondary / secondary special                       \
5122                                                 1.0    
20046                                                0.0    
11689                                                1.0    
5630                                                 1.0    
9852                                                 0.0    

       Civil marriage                                      \
5122                                                 1.0    
20046                                                0.0    
11689                                                0.0

In [75]:
train_income_mean = train['Total_Income'].mean()
print(train_income_mean)

195167.61526216296


In [76]:
gThanM = [1 if i >= train_income_mean else 0 for i in train['Total_Income']]

In [77]:
train['prediction'] = gThanM

C:\Users\User\AppData\Local\Temp/ipykernel_8396/1485942645.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['prediction'] = gThanM


In [78]:
train.head()

Applicant_Gender  Applicant_Age  Owned_Realty  Total_Children  \
15751          F                   44             0               1   
15626          F                   39             0               1   
16782          M                   30             1               0   
2380           F                   40             0               1   
14353          M                   41             1               2   

       Owned_Car  Total_Income  \
15751          0        112500   
15626          0         81000   
16782          1        225000   
2380           0        135000   
14353          1        180000   

                                            Housing_Type  \
15751  House / apartment                             ...   
15626  House / apartment                             ...   
16782  House / apartment                             ...   
2380   House / apartment                             ...   
14353  House / apartment                             ...   

       Total_Family_Members  \
15751                     3   
15626                     3   
16782                     2   
2380                      3   
14353                     4   

                                          Education_Type  \
15751  Higher education                              ...   
15626  Secondary / secondary special                 ...   
16782  Higher education                              ...   
2380   Secondary / secondary special                 ...   
14353  Higher education                              ...   

                                           Family_Status  ...  \
15751  Married                                       ...  ...   
15626  Married                                       ...  ...   
16782  Married                                       ...  ...   
2380   Married                                       ...  ...   
14353  Civil marriage                                ...  ...   

       Higher education                                    \
15751                                                1.0    
15626                                                0.0    
16782                                                1.0    
2380                                                 0.0    
14353                                                1.0    

       Incomplete higher                                   \
15751                                                0.0    
15626                                                0.0    
16782                                                0.0    
2380                                                 0.0    
14353                                                0.0    

       Lower secondary                                     \
15751                                                0.0    
15626                                                0.0    
16782                                                0.0    
2380                                                 0.0    
14353                                                0.0    

       Secondary / secondary special                       \
15751                                                0.0    
15626                                                1.0    
16782                                                0.0    
2380                                                 1.0    
14353                                                0.0    

       Civil marriage                                      \
15751                                                0.0    
15626                                                0.0    
16782                                                0.0    
2380                                                 0.0    
14353                                                1.0    

       Married                                             \
15751                                                1.0    
15626                                                1.0    
16782                                                1.0

In [79]:
y_true_num = list(train['Status'])
y_pred_num = list(train['prediction'])
#print(y_pred_num)

In [80]:
fp = 0
tp = 0
fn = 0
tn = 0
        
for i in range (len(y_true_num)):
    if y_true_num[i] == 1 and y_pred_num[i] == 1:
        tp += 1
    if y_true_num[i] == 0 and y_pred_num[i] == 1:
        fp += 1
    if y_true_num[i] == 1 and y_pred_num[i] == 0:
        fn += 1
    if y_true_num[i] == 0 and y_pred_num[i] == 0:
        tn += 1
        
precision = float (tp) / float(tp + fp)
recall = float(tp) / float(tp + fn)
        #precision1 = precision_score(y_true_num, y_pred_num)
        #print(precision1)
        #print(precision)
#precise[j] = precision
    #j += 1
print("Precision: ", precision)
print()
print("Recall: ", recall)
print()
print("False Positive: ", fp)
print()
print("False Negative: ", fn)
print()
f1 = 2*precision *recall / (precision + recall)
print("F1 Score: ", f1)

Precision:  0.9947239263803681

Recall:  0.40535

False Positive:  43

False Negative:  11893

F1 Score:  0.5759857904085257


An extrememly low f1 score indicates the baseline isnt great which is what we are aiming for but its a start and what we should beat at the very least

In [81]:
#next is to do the k-fold on the baseline of baseline models

In [82]:
#for our graphs we can use an ROC Curve to evaluate since we are doing a binary classification task
#it make sense to compare the tpr to the fpr as the roc curve does
#however we arent predicting probability anywher so it doenst make sense to use a roc curve as a result for the baseline

In [ ]:
#now we have to add each column to the dataframe


In [ ]:
#a quick graph would be to show the true positives, true negatives, false positives, and false negatives


In [ ]:
#we have a preliminary baseline but we want to get hyperparameters and so we will instead run k-fold validation

In [ ]:
#test on precision, recall and f1 score done above

In [ ]:
#try logistic regression with l1, l2, and elasticnet penalty

In [ ]:
#test on precision, recall and f1 score and this is to check hyperparameters

In [32]:
#for the graphs refer to D5 for the ROC curve for logistic regressor

# Ethics & Privacy

If your project has obvious potential concerns with ethics or data privacy discuss that here.  Almost every ML project put into production can have ethical implications if you use your imagination. Use your imagination.

Even if you can't come up with an obvious ethical concern that should be addressed, you should know that a large number of ML projects that go into producation have unintended consequences and ethical problems once in production. How will your team address these issues?

Consider a tool to help you address the potential issues such as https://deon.drivendata.org

# Team Expectations 

Put things here that cement how you will interact/communicate as a team, how you will handle conflict and difficulty, how you will handle making decisions and setting goals/schedule, how much work you expect from each other, how you will handle deadlines, etc...
* *Team Expectation 1*
* *Team Expectation 2*
* *Team Expecation 3*
* ...

# Project Timeline Proposal

UPDATE THE PROPOSAL TIMELINE ACCORDING TO WHAT HAS ACTUALLY HAPPENED AND HOW IT HAS EFFECTED YOUR FUTURE PLANS

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 1/20  |  1 PM |  Brainstorm topics/questions (all)  | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research | 
| 1/26  |  10 AM |  Do background research on topic (Pelé) | Discuss ideal dataset(s) and ethics; draft project proposal | 
| 2/1  | 10 AM  | Edit, finalize, and submit proposal; Search for datasets (Beckenbaur)  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 2/14  | 6 PM  | Import & Wrangle Data ,do some EDA (Maradonna) | Review/Edit wrangling/EDA; Discuss Analysis Plan   |
| 2/23  | 12 PM  | Finalize wrangling/EDA; Begin programming for project (Cruyff) | Discuss/edit project code; Complete project |
| 3/13  | 12 PM  | Complete analysis; Draft results/conclusion/discussion (Carlos)| Discuss/edit full project |
| 3/19  | Before 11:59 PM  | NA | Turn in Final Project  |

# Footnotes
<a name="lorenznote"></a>1.[^](#lorenz): Lorenz, T. (9 Dec 2021) Birds Aren’t Real, or Are They? Inside a Gen Z Conspiracy Theory. *The New York Times*. https://www.nytimes.com/2021/12/09/technology/birds-arent-real-gen-z-misinformation.html<br> 
<a name="admonishnote"></a>2.[^](#admonish): Also refs should be important to the background, not some randomly chosen vaguely related stuff. Include a web link if possible in refs as above.<br>
<a name="sotanote"></a>3.[^](#sota): Perhaps the current state of the art solution such as you see on [Papers with code](https://paperswithcode.com/sota). Or maybe not SOTA, but rather a standard textbook/Kaggle solution to this kind of problem
